"""Add profile_context to User

Revision ID: 3451f9589925
Revises: 4b3f9cce7b2c
Create Date: 2026-08-28 15:06:18.901894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3451f9589925'
down_revision: Union[str, None] = '4b3f9cce7b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_context')
    # ### end Alembic commands ###
